# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none 
#change back to main
parameters:
- name: environment
  displayName: 'Environment to deploy'
  type: string
  default: none
  values:
  - dev
  - stg
  - prd

- name: subscription_spn
  displayName: 'Azure Subscription'
  type: string
  default: none
  values:
  - Azure-DevOps-CP-Dev-SPN
  - Azure-DevOps-CP-Stg-SPN
  - Azure-DevOps-CP-Prod-SPN

variables:
- group: 'CP-${{parameters.environment}}-IaC'

pool:
    vmImage: 'ubuntu-latest'

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: ${{parameters.subscription_spn}}
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'aks-configuration/aks-core-service-installation.sh'
    addSpnToEnvironment: true
